[tool.poetry]
name = "initializer"
version = "1.1"
package-mode = false
description = "Kitsu Integration for Ayon"
authors = ["Martin Wacker <martin@ynput.io>", "Ahmed Gamal <agamal@mercury.com>"]

[tool.poetry.dependencies]
python = "^3.11"
gazu = "*"
nxtools = "^1.6"
ayon-python-api = "1.0.0rc3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
